/// <reference types="vite/client" />
/// <reference types="vitest/globals" />

/** Build-time injected version string from package.json (e.g. "0.1.7"). */
declare const __APP_VERSION__: string;

/**
 * Virtual module generated by the core game-discovery plugin
 * (`scripts/vite-game-discovery-plugin.ts`).
 */
declare module 'virtual:game-registry' {
  import type Phaser from 'phaser';
  import type { GameEntry } from '@ui/GameSelectorScene';

  /** The game catalogue: Gym first, then the selected game. */
  export const GAMES: GameEntry[];

  /** Every Phaser scene class to register (Gym scenes included). */
  export const SCENES: Array<typeof Phaser.Scene>;
}
