/**
 * tce single-game launcher entry point.
 *
 * AUTO-GENERATED by scripts/game-repo-scaffold.ts. Boots a Phaser game with
 * the shared GameSelectorScene; the catalogue is generated by the core
 * game-discovery plugin from `configs/game.json` (Gym + this
 * game). Engine imports resolve into the sibling core checkout via the
 * `@ui/*` path aliases.
 */
import Phaser from 'phaser';
import { createCardGame } from '@ui/createCardGame';
import { GameSelectorScene, REGISTRY_KEY_GAMES } from '@ui/GameSelectorScene';
import { GAMES, SCENES } from 'virtual:game-registry';

export { GAMES };

const isReplayMode =
  new URLSearchParams(window.location.search).get('mode') === 'replay';

createCardGame({
  backgroundColor: '#1a2a1a',
  scenes: [GameSelectorScene, ...SCENES],
  type: Phaser.CANVAS,
  render: isReplayMode ? { preserveDrawingBuffer: true } : undefined,
  callbacks: {
    preBoot: (game: Phaser.Game) => {
      game.registry.set(REGISTRY_KEY_GAMES, GAMES);
    },
  },
  exposeOnWindow: true,
});
