/// <reference types="vitest" />
/**
 * Vite config for the tce-sushi-go single-game launcher.
 *
 * AUTO-GENERATED by scripts/game-repo-scaffold.ts — edit that template rather
 * than this file so a re-scaffold does not clobber local changes.
 *
 * The engine toolchain (the config-driven game-discovery plugin and the core
 * path aliases) is imported from the sibling core checkout at `./core`.
 */
import { defineConfig } from 'vite';
import path from 'path';
import fs from 'fs';
import {
  gameDiscoveryPlugin,
  resolveCoreAliases,
} from './core/scripts/vite-game-discovery-plugin';

const coreRoot = path.resolve(__dirname, './core');
const pkg = JSON.parse(
  fs.readFileSync(path.resolve(__dirname, 'package.json'), 'utf-8'),
);
// A game repo's only preset is ./configs/game.json; the
// plugin default (core-only) applies to the core repo. GAMES_CONFIG can
// still override for an ad-hoc build.
const presetEnv = {
  ...process.env,
  GAMES_CONFIG: process.env.GAMES_CONFIG ?? 'game',
};

export default defineConfig(({ mode }) => ({
  define: {
    __APP_VERSION__: JSON.stringify(pkg.version),
  },
  // Electron loads the bundle over file://, so relative asset URLs are required.
  base: mode === 'electron' ? './' : '/',
  plugins: [
    // Reads ./configs/game.json and generates
    // 'virtual:game-registry' (Gym from the core + this one game).
    gameDiscoveryPlugin({ projectRoot: __dirname, coreRoot, env: presetEnv }),
  ],
  resolve: {
    alias: resolveCoreAliases(coreRoot),
  },
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
  server: {
    port: 3000,
    open: false,
  },
  test: {
    projects: [
      // A game repo ships only its own unit suite; browser/teacher profiles
      // live in the launcher distribution.
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'node',
          // The replay CLI subprocess inherits this: it must resolve the
          // repo's single-game preset to register the game's adapter.
          env: { GAMES_CONFIG: 'game' },
          include: ['tests/**/*.test.ts'],
          exclude: ['tests/**/*.browser.test.ts'],
          testTimeout: 15_000,
          maxWorkers: 4,
        },
      },
    ],
  },
}));
